excluded:
  - Pods
disabled_rules:
  - trailing_whitespace
  - line_length
identifier_name:
  excluded: # excluded via string array
    - id
    - URL
    - url
    - app
file_length:
  warning: 1000
  error: 1200
type_body_length:
  - 500 # warning
  - 700 # error
